# fly.toml app configuration file generated for personal-blog-api-yaw-prod on 2026-06-21T16:18:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-blog-api-yaw-prod'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
